### ISSUE TITLE
Problem z przeliczaniem waluty po dodaniu złotówki

### ISSUE THREAD

**Issue by MsHeisenbug** [NPRTEAM/NPR#1]
Po ostatnich zmianach związanych z dodaniem złotówki w plikach latest-currencies.js oraz currencyFunctions.R nie działa przeliczanie walut.

**Comment by perfiction** [comment]
Przez nieuwagę konwertowałem pole Value na łańcuch znakowy podczas kopiowania i dodawania nowego row-u. Naprawione.
